### ISSUE TITLE
overwrite addToBasket

### ISSUE THREAD

**Issue by ansgar** [6vCommerce/6vC-PayPal-Basic#10]
I have another module that overwrites the addToBasket in oxbasket. It seems that the way  6vC-PayPal-Basic overwrites addToBasket does not allow chaining with other modules. Is it possible to enable chaining for the basket?

Ansgar

**Comment by ansgar** [comment]
Maybe I just add the used basket after invoking the parent function:
public function addToBasket( $sProductID, $dAmount, $aSel = null, $aPersParam = null, $blOverride = false, $blBundle = false, $sOldBasketItemId = null )
    {
        parent::addToBasket( $sProductID, $dAmount, $aSel, $aPersParam, $blOverride, $blBundle, $sOldBasketItemId);
        foreach ($this->_aBasketContents as $sItemId => $oBasketItem) {
            $oBasketItem->v6cSetBasket($this);
        }
    }

**Comment by 6vCommerce** [comment]
Shouldn't be as simple as calling the parent because the original function is being overridden, not extended.  You'd need to merge the two functions.  The v6c mod is more like a 1-line bug fix so it should be easy to merge into the other module.  Just add

$oBasketItem->v6cSetBasket($this);

before the instance of 'oBasketItem' is used.

This is not really an issue with the 6vC-PayPal-Basic module, it's just the nature of overriding functions in php.

**Comment by ansgar** [comment]
Hmm.
I can't fully agree with your statement, though I think I understand the main point of problems in overriding functions.
If I add your line to my module one of the nice aspects of modularity gets lost. To me that approach seems like modifying my car to have sliding doors because I can't open my normal door on a parking lot with an oversized car next to mine. ;-)
